// src/components/PostItem.jsx
import React from 'react'
import { useHistory } from 'react-router-dom';
import MyButton from './UI/button/MyButton';

const PostItem = (props) => {
    const router = useHistory()
    return (
        <div className='post'>
            <div className='post__content'>
                <strong>{props.post.id}.{props.post.title}</strong>
                <div>{props.post.body}</div>
            </div>
            <div className='post__btns'>
                <MyButton onClick={() => router.push(`/posts/${props.post.id}`)}>
                    Open
                </MyButton>
                <MyButton onClick={() => props.remove(props.post)}>
                    Delete
                </MyButton>
            </div>
        </div>
    );
}

export default PostItem;

// src/components/PostItem.vue
<template>
  <div class="post">
    <div>
      <div>{{post.id}}</div>
      <div><strong>Title:</strong>{{ post.title }}</div>
      <div><strong>Description:</strong>{{ post.body }}</div>
    </div>
    <div class="post__btns">
      <my-button 
      @click="$router.push(`/posts/${post.id}`)">Open</my-button>
      <my-button 
      @click="$emit('remove', post)">Delete</my-button>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    post: {
      type: Object,
      required: true,
    },
  },
};
</script>

<style scoped>
.post {
  padding: 15px;
  border: 2px solid teal;
  margin-top: 15px;
  display: flex;
  align-items: center;
  justify-content: space-between;
}
.post__btns{
  display: flex;
}
</style>
